In [2]:
import numpy as np

array1 = np.array([1, 2, 3])
print(f"array1 type:{type(array1)}")
print(f"array1 array 형태: {array1.shape}")

array2 = np.array([[1, 2, 3],
                  [2, 3, 4]])
print(f"array2 type:{type(array2)}")
print(f"array2 array 형태:{array2.shape}")

array3 = np.array([[1, 2, 3]])
print(f"array3 type:{type(array3)}")
print(f"array3 array 형태:{array3.shape}")

array1 type:<class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type:<class 'numpy.ndarray'>
array2 array 형태:(2, 3)
array3 type:<class 'numpy.ndarray'>
array3 array 형태:(1, 3)


In [2]:
print(f"array1: {array1.ndim}차원, array2: {array2.ndim}차원, array3: {array3.ndim}차원")

array1: 1차원, array2: 2차원, array3: 2차원


In [5]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [6]:
#int -> float
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

#float -> int
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

#float -> int
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [14]:
#arange()

array1 = np.arange(10)
print(array1)
print(array1.dtype, array1.shape)

array2 = np.arange(0, 10)
print(array2)

array3 = np.arange(5, 10)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]


In [15]:
#zeros()

z_a = np.zeros((3, 2), dtype= 'int32')
print(z_a)
print(z_a.dtype, z_a.shape)

#ones
o_a = np.ones((3, 2)) # no dtype -> default ( float64 )
print(o_a)
print(o_a.dtype, o_a.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [20]:
#reshape() 특정 차원 및 크기로 변환

arr1 = np.arange(10)
print(f'arr1:\n{arr1}')

arr2 = arr1.reshape(2, 5)
print(f'arr2:\n{arr2}')

arr3 = arr1.reshape(5, 2)
print(f'arr3:\n{arr3}')

arr1:
[0 1 2 3 4 5 6 7 8 9]
arr2:
[[0 1 2 3 4]
 [5 6 7 8 9]]
arr3:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [33]:
#reshape()에 -1값을 인자로 주기
#ndarray와 호환되는 새로운 shape으로 변환해준다.

arr1 = np.arange(10)
print(arr1)
arr2 = arr2.reshape(-1, 5)
print(f'arr2 shape :{arr2.shape}')
print(f'arr2: \n{arr2}')
arr3 = arr1.reshape(5, -1)
print(f'arr3 shape :{arr3.shape}')
print(f'arr3: \n{arr3}')
arr4 = arr1.reshape(10, -1)
print(f"arr4 shape :{arr4.shape}")
print(f"arr4: \n{arr4}")

[0 1 2 3 4 5 6 7 8 9]
arr2 shape :(2, 5)
arr2: 
[[0 1 2 3 4]
 [5 6 7 8 9]]
arr3 shape :(5, 2)
arr3: 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
arr4 shape :(10, 1)
arr4: 
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [6]:
#tolist()메서드를 사용
#ndarray -> list

a1 = np.arange(8)
a3d = a1.reshape((2, 2, 2))
print(f'a3d:\n{a3d.tolist()}')

#3D ndarray -> 2D ndarray

a5 = a3d.reshape(-1, 1)
print(f'a5:\n{a5.tolist()}')
print(f'a5 shape: {a5.shape}')

#1D ndarray -> 2D ndarray
a6 = a1.reshape(-1, 1)
print(f'a6:\n{a6.tolist()}')
print(f'a6.shape:{a6.shape}')

a3d:
[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
a5:
[[0], [1], [2], [3], [4], [5], [6], [7]]
a5 shape: (8, 1)
a6:
[[0], [1], [2], [3], [4], [5], [6], [7]]
a6.shape:(8, 1)


In [5]:
arr1 = np.arange(start=1, stop=10)
print(f'arr1: {arr1}')

value = arr1[2]
print(f'value: {value}')
print(type(value))

arr1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [7]:
print(f'last : {arr1[-1]} second form behind : {arr1[-2]}')

last : 9 second form behind : 8


In [8]:
arr1[0] = 500
print(arr1)

[500   2   3   4   5   6   7   8   9]


In [9]:
arr1 = np.arange(1, 10)
arr3 = arr1[0:3]
print(arr3)
print(type(arr3))

[1 2 3]
<class 'numpy.ndarray'>


In [20]:
arr1d = np.arange(1, 10)
arr2d = arr1d.reshape(3, 3)
print(f'arr2d : \n{arr2d}')

print(f"arr2d : \n{arr2d[0:2, 0:2]}")

arr2d : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr2d : 
[[1 2]
 [4 5]]


In [19]:
#2. 슬라이싱
#ndarray indexing으로 범위 설정하여 출력하기

#1차원 ndarray
arr1d = np.arange(1, 10)

#1차원 ndarray -> reshape 2차원 ndarray
arr2d = arr1d.reshape(3, 3)

print(arr2d)

#2d ndarray를 indexing하여 출력
print(f"\n{arr2d[:2, :2]}")
# =
print(f"\n{arr2d[0:2,0:2]}")

print(f"\n{arr2d[1:2, :2]}")
# =
print(f"\n{arr2d[1:2, 0:2]}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2]
 [4 5]]

[[1 2]
 [4 5]]

[[4 5]]

[[4 5]]


In [28]:
#3. 팬시 인덱싱, Fancy Indexing
# 리스트, ndarray로 인덱스 집합을 지정하면 
# 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식
# 인덱스한 위치의 ndarray를 반환
# ?? 슬라이싱과 펜시 인덱싱과 차이점은  무엇인가

#슬라이싱
arr1d = np.arange(1, 10)
arr2d = arr1d.reshape(3, 3)

print(arr2d[:2, :2], '\n')

#팬시 인덱싱

print(arr2d[[0, 1], 0:2])

[[1 2]
 [4 5]] 

[[1 2]
 [4 5]]
